name: Super staff
main: me.sehplayz.core.StaffCore
version: 0.1
commands:
    ban:
      description: 'Bans a Player'
    kick:
      description: 'Kicks a Player'
    staff:
      description: 'Go in Staff mode'